#!/bin/sh

##
## Setup ASE environment using ../rtl/sources.txt.
##

# Absolute path to this script
SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")

# Use VCS as long as it is present
SIMULATOR='vcs'
if [ ! -x "$(command -v ${SIMULATOR})" ]; then
  SIMULATOR='questa'
fi

setup_afu_sim --sources=${SCRIPT_PATH}/../rtl/sources.txt $*
