#!/bin/sh

##
## This script should be installed in the top-level bin directory of an FPGA
## platform release.  The script sets FPGA_RELEASE_DIR to point to the release
## directory and invokes the common afu_synth_setup_std in OPAE.
##

# Get exact script path
SCRIPT_PATH=`readlink -f "$0"`
# Get directory of script path
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

# OPAE afu_synth_setup_std expects a pointer to the release directory
if [ "$FPGA_RELEASE_DIR" == "" ]; then
    export FPGA_RELEASE_DIR="${PARENT_DIR}"
fi

# Invoke OPAE common script
afu_synth_setup_std $@
